# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Freeciv21 and Freeciv Contributors
# SPDX-FileCopyrightText: XHawk87 <hawk87@hotmail.co.uk>

FROM debian:stable-20260406-slim

ARG DEBIAN_FRONTEND=noninteractive
ARG CMAKE_BUILD_TYPE=Debug
ARG INSTALL_DIR=./build-docker/install
ARG UID=556
ARG GID=${UID}

# Copy installed files from builder
COPY ${INSTALL_DIR}/bin/freeciv21-server /usr/bin/freeciv21-server
COPY ${INSTALL_DIR}/share/freeciv21 /usr/share/freeciv21

# Minimal runtime deps
RUN bash <<'END_RUN'
set -e
deps=(
    libqt6gui6=6.8.2+dfsg-9+deb13u2
    libkf6archive6=6.13.0-2
    liblua5.3-0=5.3.6-2+b4
    libreadline8t64=8.2-6
    libqt6network6=6.8.2+dfsg-9+deb13u2
    luarocks=3.8.0+dfsg1-1
    lua5.3=5.3.6-2+b4
    liblua5.3-dev=5.3.6-2+b4
    libsqlite3-dev=3.46.1-7+deb13u2
    libpq-dev=17.11-0+deb13u1
    build-essential=12.12
    pkg-config=1.8.1-4
)
if [[ ${CMAKE_BUILD_TYPE} == "Debug" ]]; then
  deps+=(
      libunwind-dev=1.8.1-0.1
      libdw-dev=0.192-4
      gdb=16.3-1
  )
fi
apt-get update && apt-get install -y --no-install-recommends "${deps[@]}"
rm -rf /var/lib/apt/lists/*
mkdir -p /usr/local/share/freeciv21
groupadd --system --gid ${GID} freeciv21
useradd --create-home --home-dir /home/freeciv21 \
        --system --uid ${UID} --gid freeciv21 \
        --shell /usr/sbin/nologin freeciv21
chown freeciv21:freeciv21 /home/freeciv21
eval $(luarocks path --bin --lua-version 5.3)
luarocks --lua-version 5.3 install md5 1.3-1
luarocks --lua-version 5.3 install luasql-sqlite3 2.8.0-1
luarocks --lua-version 5.3 install luasql-postgres 2.8.0-1 \
    PGSQL_INCDIR=/usr/include/postgresql PGSQL_LIBDIR=/usr/lib
END_RUN

EXPOSE 5556/tcp

USER freeciv21
WORKDIR /home/freeciv21

ENTRYPOINT ["/usr/bin/freeciv21-server"]
